version: '3.9'
services:
  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: Nurik
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: queue_db
    volumes:
      - ./data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 core.wsgi"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db

  nginx:
    image: nginx:1.19.8-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./static:/usr/share/nginx/html/static
    depends_on:
      - web
