version: '3'
services:
  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: Nurik
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: queue_db
    volumes:
      - ./data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db