version: '3'
services:
  db:
    image: postgres
    environment:
      DB_USER: Nurik
      DB_PASSWORD: 1
      DB_DB: queue_db
    volumes:
      - ./database_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
    