# Generated by Django 4.2.2 on 2023-06-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='window_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
