# Generated by Django 4.2.2 on 2023-06-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0002_queue_window_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='average_waiting_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
