# Generated by Django 4.2.2 on 2023-06-16 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('qsystem', '0003_queue_average_waiting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.terminal'),
        ),
        migrations.AddField(
            model_name='queue',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
    ]
