# Generated by Django 4.2.2 on 2023-06-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0004_customer_terminal_queue_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_served',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
