# Generated by Django 4.2.2 on 2023-06-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0005_alter_customer_is_served'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='terminal',
        ),
    ]
