# Generated by Django 4.2.2 on 2023-06-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0006_remove_customer_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ticket_number',
            field=models.CharField(),
        ),
    ]
