# Generated by Django 4.2.2 on 2023-06-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0008_queue_operator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-position'], 'verbose_name': 'Талон', 'verbose_name_plural': 'Талоны'},
        ),
        migrations.AddField(
            model_name='customer',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ticket_number',
            field=models.CharField(max_length=10),
        ),
    ]
