# Generated by Django 4.2.2 on 2023-06-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0009_alter_customer_options_customer_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='kpi',
            field=models.FloatField(default=0),
        ),
    ]
