# Generated by Django 4.2.2 on 2023-06-22 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qsystem', '0010_queue_kpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='kpi',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='window_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.CharField(choices=[('regular', 'Обычный'), ('pensioner', 'Пенсионер'), ('pregnant', 'Беременная'), ('veteran', 'Ветеран'), ('disabled person', 'С ограниченными возможностями')], default='regular', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queue',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='max_waiting_time',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='queue',
            name='schedule_end',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='queue',
            name='schedule_start',
            field=models.PositiveIntegerField(default=9),
        ),
        migrations.RemoveField(
            model_name='queue',
            name='operator',
        ),
        migrations.AddField(
            model_name='queue',
            name='operator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
