# Generated by Django 4.2.2 on 2023-06-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0011_remove_queue_branch_remove_queue_kpi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='symbol',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
