# Generated by Django 4.2.2 on 2023-06-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0012_queue_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='types',
            field=models.CharField(choices=[('individuals', 'Физические лица'), ('legal entities', 'Юридические лица'), ('payment cards', 'Платежные карты')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
