# Generated by Django 4.2.2 on 2023-06-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0013_queue_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
