# Generated by Django 4.2.2 on 2023-06-22 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0004_window'),
        ('qsystem', '0014_customer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='window',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branches.window'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='queue',
            name='operator',
            field=models.ManyToManyField(related_name='queues', to=settings.AUTH_USER_MODEL),
        ),
    ]
