# Generated by Django 4.2.2 on 2023-06-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0015_customer_window_alter_queue_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='window',
        ),
    ]
