# Generated by Django 4.2.2 on 2023-06-23 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qsystem', '0016_remove_customer_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='served_start',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
