# Generated by Django 4.2.2 on 2023-06-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0017_customer_operator_customer_served_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number_of_transfers',
            field=models.PositiveSmallIntegerField(default=0, max_length=10),
        ),
    ]
