# Generated by Django 4.2.2 on 2023-06-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0018_customer_number_of_transfers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='number_of_transfers',
        ),
    ]
