# Generated by Django 4.2.2 on 2023-06-23 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_window_number_of_transfers'),
        ('qsystem', '0019_remove_customer_number_of_transfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.window'),
        ),
    ]
