# Generated by Django 4.2.2 on 2023-06-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0021_alter_customer_operator_alter_customer_queue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_out_of_turn',
            field=models.BooleanField(default=False),
        ),
    ]
