# Generated by Django 4.2.2 on 2023-06-23 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0022_customer_is_out_of_turn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_out_of_turn',
        ),
        migrations.CreateModel(
            name='Waiting_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qsystem.customer')),
            ],
        ),
    ]
