# Generated by Django 4.2.2 on 2023-06-23 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qsystem', '0023_remove_customer_is_out_of_turn_waiting_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='old_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers_at_old_operator', to=settings.AUTH_USER_MODEL),
        ),
    ]
