# Generated by Django 4.2.2 on 2023-06-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0024_customer_old_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number_of_calls',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
