# Generated by Django 4.2.2 on 2023-06-23 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_window_is_online'),
        ('qsystem', '0025_customer_number_of_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='branches.branch'),
        ),
    ]
