# Generated by Django 4.2.2 on 2023-06-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0026_queue_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='schedule_end',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='schedule_start',
        ),
    ]
