# Generated by Django 4.2.2 on 2023-06-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0027_remove_queue_schedule_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='documents',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='optional_documents',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
