# Generated by Django 4.2.2 on 2023-06-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0028_queue_documents_queue_optional_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('individuals', 'Физические лица'), ('legal entities', 'Юридические лица'), ('payment cards', 'Платежные карты')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='queue',
            name='types',
        ),
    ]
