# Generated by Django 4.2.2 on 2023-06-24 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0029_services_remove_queue_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='qsystem.services'),
        ),
    ]
