# Generated by Django 4.2.2 on 2023-06-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0030_queue_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='category',
            field=models.CharField(choices=[('regular', 'Обычный'), ('booked', 'По записи'), ('pensioner', 'Пенсионер'), ('pregnant', 'Беременная'), ('veteran', 'Ветеран'), ('disabled person', 'С ограниченными возможностями')], max_length=20),
        ),
    ]
