# Generated by Django 4.2.2 on 2023-06-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0031_customer_time_alter_customer_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Талон', 'verbose_name_plural': 'Талоны'},
        ),
        migrations.AlterModelOptions(
            name='waiting_list',
            options={'verbose_name': 'Лист ожидания', 'verbose_name_plural': 'Лист ожидания'},
        ),
    ]
