# Generated by Django 4.2.2 on 2023-07-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0033_remove_customer_user_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='documents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='optional_documents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
