# Generated by Django 4.2.2 on 2023-07-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0034_alter_queue_documents_alter_queue_optional_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='max_calls',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
