# Generated by Django 4.2.2 on 2023-07-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0035_queue_max_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='print_end',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='queue',
            name='print_start',
            field=models.TimeField(default='9:00'),
        ),
    ]
