# Generated by Django 4.2.2 on 2023-07-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0036_queue_print_end_queue_print_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
