# Generated by Django 4.2.2 on 2023-07-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0037_queue_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='waiting_time_operator',
            field=models.PositiveIntegerField(default=120),
        ),
    ]
