# Generated by Django 4.2.2 on 2023-07-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0038_queue_waiting_time_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='auto_transfer',
            field=models.BooleanField(default=True),
        ),
    ]
