# Generated by Django 4.2.2 on 2023-07-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0040_alter_services_options_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='max_transfers',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
