# Generated by Django 4.2.2 on 2023-06-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_birth_date_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_operator',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='users/default.jpg', null=True, upload_to='users'),
        ),
        migrations.AddField(
            model_name='profile',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('guest', 'Гость'), ('operator', 'Оператор'), ('admin', 'Admin')], default='guest', max_length=20),
        ),
    ]
