# Generated by Django 4.2.2 on 2023-07-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('operator', 'Оператор'), ('admin', 'Admin'), ('registrator', 'Регистратор')], default='operator', max_length=20),
        ),
    ]
