# Generated by Django 4.2.2 on 2023-07-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('operator', 'Оператор'), ('admin', 'Admin'), ('registrator', 'Регистратор'), ('regular', 'Посетитель')], default='regular', max_length=20),
        ),
    ]
