# Generated by Django 4.2.2 on 2023-07-17 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qsystem', '0039_queue_auto_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('created', 'Создан'), ('cancelled', 'Отменен'), ('served', 'Обслужен'), ('shifted', 'Перевен')], max_length=150)),
                ('event', models.CharField(max_length=150)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='qsystem.customer')),
            ],
        ),
    ]
