# Generated by Django 4.2.2 on 2023-06-25 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qsystem', '0031_customer_time_alter_customer_category'),
        ('branches', '0014_window_is_busy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pin', models.IntegerField(max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='branches.branch')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='qsystem.queue')),
            ],
        ),
    ]
