# Generated by Django 4.2.2 on 2023-06-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_date_alter_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
