# Generated by Django 4.2.2 on 2023-06-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_is_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='branch',
        ),
    ]
