# Generated by Django 4.2.2 on 2023-07-07 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_served', models.PositiveIntegerField(default=0)),
                ('average_time', models.PositiveIntegerField(default=0)),
                ('max_time', models.PositiveIntegerField(default=0)),
                ('min_time', models.PositiveIntegerField(default=0)),
                ('operator_first_name', models.CharField(blank=True, max_length=100)),
                ('operator_last_name', models.CharField(blank=True, max_length=100)),
                ('operator_surname', models.CharField(blank=True, max_length=100)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operator Report',
                'verbose_name_plural': 'Operator Reports',
            },
        ),
    ]
