# Generated by Django 4.2.2 on 2023-07-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorreport',
            name='date',
            field=models.DateField(),
        ),
    ]
