# Generated by Django 4.2.2 on 2023-07-08 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_alter_operatorreport_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OperatorReport',
            new_name='OperatorDailyReport',
        ),
        migrations.CreateModel(
            name='OperatorServedCustomerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('served_time', models.TimeField()),
                ('operator_first_name', models.CharField(blank=True, max_length=100)),
                ('operator_last_name', models.CharField(blank=True, max_length=100)),
                ('operator_surname', models.CharField(blank=True, max_length=100)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='served_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
