# Generated by Django 4.2.2 on 2023-07-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_rename_operatorreport_operatordailyreport_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperatorServedCustomerReport',
        ),
    ]
