# Generated by Django 4.2.2 on 2023-07-10 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qsystem', '0039_queue_auto_transfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0004_delete_operatorservedcustomerreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=150)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=150)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='qsystem.customer')),
            ],
        ),
    ]
