# Generated by Django 4.2.2 on 2023-07-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_operatoraction_customeraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatoraction',
            name='action',
            field=models.CharField(choices=[('come', 'Вошел'), ('out', 'Вышел'), ('started', 'Начал Обслуживать'), ('served', 'Обслужил'), ('cancelled', 'Отменил'), ('shifted', 'Перевел')], max_length=150),
        ),
    ]
