# Generated by Django 4.2.2 on 2023-07-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_operatoraction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraction',
            name='action',
            field=models.CharField(choices=[('created', 'Создан'), ('cancelled', 'Отменен'), ('served', 'Обслужен'), ('shifted', 'Перевен')], max_length=150),
        ),
    ]
