# Generated by Django 4.2.2 on 2023-07-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_customeraction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatoraction',
            name='customer_id',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
