# Generated by Django 4.2.2 on 2023-07-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_operatoraction_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraction',
            name='event',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operatoraction',
            name='event',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
