# Generated by Django 4.2.2 on 2023-07-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_customeraction_event_operatoraction_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatoraction',
            name='customer_id',
        ),
    ]
