# Generated by Django 4.2.2 on 2023-07-10 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_remove_operatoraction_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraction',
            old_name='Customer',
            new_name='customer',
        ),
    ]
