# Generated by Django 4.2.2 on 2023-06-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='number',
        ),
    ]
