# Generated by Django 4.2.2 on 2023-06-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_remove_branch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
