# Generated by Django 4.2.2 on 2023-06-20 06:54

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_remove_branch_number_branch_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=1, max_length=63),
            preserve_default=False,
        ),
    ]
