# Generated by Django 4.2.2 on 2023-06-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='number_of_transfers',
            field=models.PositiveSmallIntegerField(default=0, max_length=10),
        ),
    ]
