# Generated by Django 4.2.2 on 2023-06-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_window_number_of_transfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='max_transfers',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='window',
            name='number_of_transfers',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
