# Generated by Django 4.2.2 on 2023-06-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_window_max_transfers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
