# Generated by Django 4.2.2 on 2023-06-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_window_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='schedule_end',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='schedule_start',
            field=models.IntegerField(default=9),
        ),
    ]
