# Generated by Django 4.2.2 on 2023-06-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0009_region_branch_city_branch_street_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='address',
        ),
    ]
