# Generated by Django 4.2.2 on 2023-06-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0010_remove_branch_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='schedule_end',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='window',
            name='schedule_start',
            field=models.IntegerField(default=9),
        ),
    ]
