# Generated by Django 4.2.2 on 2023-06-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0011_window_schedule_end_window_schedule_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='location',
        ),
    ]
