# Generated by Django 4.2.2 on 2023-06-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0013_branch_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
    ]
