# Generated by Django 4.2.2 on 2023-06-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0014_window_is_busy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='schedule_end',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='schedule_start',
        ),
    ]
