# Generated by Django 4.2.2 on 2023-06-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0015_remove_branch_schedule_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='schedule_end',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='branch',
            name='schedule_start',
            field=models.TimeField(default='9:00'),
        ),
    ]
