# Generated by Django 4.2.2 on 2023-06-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0016_branch_schedule_end_branch_schedule_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='window',
            options={'verbose_name': 'Окно', 'verbose_name_plural': 'Окна'},
        ),
    ]
