# Generated by Django 4.2.2 on 2023-07-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0018_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
