# Generated by Django 4.2.2 on 2023-07-20 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0020_floor_cabinet_window_cabinet_window_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('content', models.FileField(upload_to='ad_contents/')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text_size', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('сoursive', models.BooleanField(default=False)),
                ('italic', models.BooleanField(default=False)),
                ('bold', models.BooleanField(default=False)),
                ('speed', models.IntegerField(default=2)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='branches.branch')),
            ],
        ),
        migrations.DeleteModel(
            name='Terminal',
        ),
        migrations.AddField(
            model_name='ad',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='branches.board'),
        ),
    ]
