# Generated by Django 4.2.2 on 2023-07-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0021_ad_board_delete_terminal_ad_board'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Реклама', 'verbose_name_plural': 'Рекламы'},
        ),
        migrations.AlterModelOptions(
            name='basecalendar',
            options={'verbose_name': 'День', 'verbose_name_plural': 'Общий календарь'},
        ),
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Табло', 'verbose_name_plural': 'Таблы'},
        ),
        migrations.AlterModelOptions(
            name='cabinet',
            options={'verbose_name': 'Кабинет', 'verbose_name_plural': 'Кабинеты'},
        ),
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name': 'День', 'verbose_name_plural': 'Календарь'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name': 'Этаж', 'verbose_name_plural': 'Этажи'},
        ),
    ]
