# Generated by Django 4.2.2 on 2023-07-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0022_alter_ad_options_alter_basecalendar_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='window',
            name='max_transfers',
        ),
    ]
