# Generated by Django 4.2.2 on 2023-07-24 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0023_remove_window_max_transfers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.CharField(default='Bishkek', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='branches.region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='street',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='window',
            name='cabinet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branches.cabinet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='window',
            name='floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branches.floor'),
            preserve_default=False,
        ),
    ]
